name: Simple CI

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Message
        run: echo "Hello! GitHub Actions is working."

      - name: Show Files
        run: ls -la
